import { Lalezar, Lato, Roboto } from "next/font/google";
import "./globals.css";

const lalezar = Lalezar({
  weight:"400",
  variable: "--font-lalezar",
  subsets: ["latin"],
});

// const lato = Lato({
//   variable: "--font-lato",
//   subsets: ["latin"],
// });

// const roboto = Roboto({
//   variable: "--font-roboto",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "PharmaCheck",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lalezar.variable}  antialiased`}
        // className={`${lalezar.variable} ${lato.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
